/// Smoothly interpolate between [start] and [end].
///
/// Generated by ChatGPT.
double smoothstep(double start, double end, double x) {
  x = (x - start) / (end - start);
  x = x * x * (3 - 2 * x);
  return start + x * (end - start);
}

/// Linearly interpolate between [a] and [b], at [f].
///
/// [f] will be clamped between zero and one.
double lerp(double a, double b, double f) {
  f = f.clamp(0, 1);
  return a * (1.0 - f) + (b * f);
}

/// Get the absolute value of [x].
num abs(num x) => x < 0 ? -x : x;
